from enum import Enum


class CaseStatus(str, Enum):
    DETECTED = "DETECTED"
    CONTEXT_BUILT = "CONTEXT_BUILT"
    DIAGNOSED = "DIAGNOSED"
    PLANNING = "PLANNING"
    SCORE_EV = "SCORE_EV"
    POLICY_CHECK = "POLICY_CHECK"
    ACTION_EXECUTING = "ACTION_EXECUTING"
    WAITING_FOR_OUTCOME = "WAITING_FOR_OUTCOME"
    RECOVERED = "RECOVERED"
    EXPIRED = "EXPIRED"
    ESCALATED = "ESCALATED"
    CLOSED_NO_RECOVERY = "CLOSED_NO_RECOVERY"
    REJECTED_BY_POLICY = "REJECTED_BY_POLICY"
    REFUNDED = "REFUNDED"
    DISPUTED = "DISPUTED"


class CaseType(str, Enum):
    FAILED_PAYMENT = "FAILED_PAYMENT"
    ABANDONED_CHECKOUT = "ABANDONED_CHECKOUT"
    OVERDUE_INVOICE = "OVERDUE_INVOICE"


class EventType(str, Enum):
    PAYMENT_FAILED = "PAYMENT_FAILED"
    CHECKOUT_ABANDONED = "CHECKOUT_ABANDONED"
    INVOICE_OVERDUE = "INVOICE_OVERDUE"
    PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
    COMMUNICATION_DELIVERED = "COMMUNICATION_DELIVERED"
    PROMISE_MADE = "PROMISE_MADE"
    PROMISE_BROKEN = "PROMISE_BROKEN"
    GATEWAY_HEALTH_UPDATE = "GATEWAY_HEALTH_UPDATE"


class InterventionType(str, Enum):
    RETRY_PAYMENT = "RETRY_PAYMENT"
    SWITCH_GATEWAY = "SWITCH_GATEWAY"
    CREATE_PAYMENT_LINK = "CREATE_PAYMENT_LINK"
    SEND_DISCOUNT_MESSAGE = "SEND_DISCOUNT_MESSAGE"
    SEND_REMINDER = "SEND_REMINDER"
    ESCALATE_TO_HUMAN = "ESCALATE_TO_HUMAN"
    OFFER_PAYMENT_PLAN = "OFFER_PAYMENT_PLAN"
    VERIFY_PROMISE = "VERIFY_PROMISE"
    NO_ACTION = "NO_ACTION"


class OutcomeType(str, Enum):
    RECOVERED_FULL = "RECOVERED_FULL"
    RECOVERED_PARTIAL = "RECOVERED_PARTIAL"
    EXPIRED = "EXPIRED"
    FAILED_PERMANENT = "FAILED_PERMANENT"
    ESCALATED = "ESCALATED"
    PENDING = "PENDING"
    REFUNDED = "REFUNDED"


class EscalationReason(str, Enum):
    AMOUNT_EXCEEDS_POLICY = "AMOUNT_EXCEEDS_POLICY"
    MAX_RETRIES_EXCEEDED = "MAX_RETRIES_EXCEEDED"
    HIGH_LTV_CUSTOM_HANDLING = "HIGH_LTV_CUSTOM_HANDLING"
    AGENT_LOW_CONFIDENCE = "AGENT_LOW_CONFIDENCE"
    POLICY_REJECTION = "POLICY_REJECTION"
    MANUAL_REQUEST = "MANUAL_REQUEST"
    DISPUTE_FILED = "DISPUTE_FILED"


class Priority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"


class ChannelType(str, Enum):
    EMAIL = "EMAIL"
    WHATSAPP = "WHATSAPP"
    SMS = "SMS"
    IN_APP = "IN_APP"


class PromiseStatus(str, Enum):
    PENDING = "PENDING"
    FULFILLED = "FULFILLED"
    BROKEN = "BROKEN"
    EXTENDED = "EXTENDED"


class EscalationResolutionStatus(str, Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
